name: Save Commit History
on: [push, pull_request]

permissions:
      contents: write
      issues: write
      pull-requests: write

jobs:
  show-commits:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: List commits and save to file
      run: |
        git fetch;
        git log --pretty=format:"Author: %an, Date: %ad, Title: %s" --date=short > commit_log.txt
        cat commit_log.txt
    
    - name: Push to Github
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add commit_log.txt
        git commit -m "Update Commit Logs"
        git push
      
