name: Save Commit History
on: [push, pull_request]

permissions:
      contents: write
      issues: write
      pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ACTIONS_RUNNER_DEBUG: true
      ACTIONS_STEP_DEBUG: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all commit history

      - name: Save commit history to file
        run: |
          git log -1 --pretty=format:"%an <%ae>" > commit_author_info.txt
          cat commit_author_info.txt
