name: Save Commit History
on: [push, pull_request]

permissions:
      contents: write
      issues: write
      pull-requests: write

jobs:
  show-commits:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: List commits and save to file
      run: |
        git log --pretty=format:"Author: %an, Date: %ad, Title: %s" --date=short > commit_log.txt
        cat commit_log.txt
