name: Save Commit History
disable temp
on: [push, pull_request]

permissions:
      contents: write
      issues: write
      pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all commit history

      - name: Save commit history to file
        run: |
          git log --oneline > commit_history.txt
          cat commit_history.txt

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add commit_history.txt
          git commit -m 'Save commit history'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
