name: Update README

on:
  push:
    branches:
      - main

permissions:
      contents: write
      issues: write
      pull-requests: write

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Fetch commit data
      run: |
        curl -H "Authorization: token ${{ secret.GH_TOKEN }}" \
        "https://api.github.com/repos/${{ github.repository }}/commits?since=$(date -d '7 days ago' --utc +%Y-%m-%dT%H:%M:%SZ)" \
        > commits.json

    - name: Process commit data
      run: |
        jq -r '.[] | .commit.author.name' commits.json | sort | uniq -c | sort -nr > commit_counts.txt

    - name: Update README
      run: |
        # Read the current README
        readme=$(cat README.md)
        
        # Extract the part before the marker
        before_marker=$(echo "$readme" | sed -n '1,/<!-- COMMIT_SECTION_START -->/p')
        
        # Extract the part after the marker
        after_marker=$(echo "$readme" | sed -n '/<!-- COMMIT_SECTION_END -->/,$p')
        
        # Create the new content
        new_content=$(cat commit_counts.txt)
        
        # Combine the parts
        echo "$before_marker" > README.md
        echo "<!-- COMMIT_COUNTS_START -->" >> README.md
        echo "$new_content" >> README.md
        echo "<!-- COMMIT_COUNTS_END -->" >> README.md
        echo "$after_marker" >> README.md

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add README.md
        git commit -m "Update README with weekly commit counts"
        git push
