name: Update README

on:
  push:
    branches:
      - main

permissions:
      contents: write
      issues: write
      pull-requests: write

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Set up debug logging
      run: echo "GITHUB_ACTIONS=true" >> $GITHUB_ENV

    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Pull and Rebase
      run: | 
        git pull --rebase origin main
    
    - name: Fetch commit data
      run: |
        # echo $PWD
        echo "$(git log | git shortlog -sn --since="7 days ago")" > commit_counts.txt
        cat commit_counts.txt

    # - name: Clone and Test
    #   run: | 
    #     git clone https://github.com/elu211/HHSSciOlyWebsite
    #     cd HHSSciOlyWebsite
    #     ls
    #     git fetch
    #     echo "$(git log --since="1 week ago" --pretty=short | git shortlog -sn)" > commit_counts.txt
        
        
    - name: Update README
      run: |
        # Read the current README
        readme=$(cat README.md)
        
        # Extract the part before the marker
        before_marker=$(echo "$readme" | sed -n '1,/<!-- COMMIT_SECTION_START -->/p')
        
        # Extract the part after the marker
        after_marker=$(echo "$readme" | sed -n '/<!-- COMMIT_SECTION_END -->/,$p')

        echo $PWD
        ls
        
        # Create the new content
        new_content=$(cat commit_counts.txt)
        
        # Combine the parts
        echo "$before_marker" > README.md
        echo "<!-- COMMIT_COUNTS_START -->" >> README.md
        echo "$new_content" >> README.md
        echo "<!-- COMMIT_COUNTS_END -->" >> README.md
        echo "$after_marker" >> README.md

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/elu211/HHSSciOlyWebsite.git
        git add README.md
        git commit -m "Update README with weekly commit counts"
        git push origin main
      env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
